### ISSUE TITLE
Issue connecting to iOS app

### ISSUE THREAD

**Issue by stopshinal** [NordicSemiconductor/nrf8001-ble-uart-spark-io#1]
Has this library been tested against iOS connectivity yet?

I've been successful connecting the nRF8001 to an Arduino and interacting with it via various nRF8001 iOS bluetooth apps ie: [Adafruit's Bluefruit LE](https://itunes.apple.com/us/app/adafruit-bluefruit-le-connect/id830125974?mt=8)

However,  I have not been successful while using the spark core as the microcontroller and using the nRF UART _not v2_ app.

![img_4373](https://cloud.githubusercontent.com/assets/1017476/5219413/bec758d8-7614-11e4-8a49-ef4aee742dd3.JPG)
![img_4374](https://cloud.githubusercontent.com/assets/1017476/5219415/becfa16e-7614-11e4-983e-2405481e958e.JPG)
![img_4375](https://cloud.githubusercontent.com/assets/1017476/5219414/bec894e6-7614-11e4-9651-73d02d4f960b.PNG)

**Comment by gotnull** [comment]
Okay, phew! I thought it was just me. I have the exact same Adafruit BLE module and a SparkCore and I'm also able to connect to the [Adafruit Bluefruit LE Connect
](https://itunes.apple.com/us/app/adafruit-bluefruit-le-connect/id830125974?mt=8) iOS app, however am not able to connect to the official [nRF UART](https://itunes.apple.com/au/app/nrf-uart/id614594903?mt=8) iOS app.

I get the exact same issue you're getting when it just sits there saying "Scanning..."

**Comment by trond-snekvik** [comment]
Sorry for the delay on this issue.
In order to enable dynamic name setting for the Spark version of the framework, the GATT service list was moved from the advertisements to the scan response to provide more space. The Android application (nRF UART 2.0) handles this just fine, but the iOS application only connects to devices which advertise the UART Service, and would just ignore the Spark version of the framework. 

I just pushed a fix for this issue by putting the GATT service list back in the advertisement message, which appears to solve the issue. I've tested and verified it with an iPhone 4S running iOS7.1, and will push the fix to the spark.io/build library as version 0.6.1. @stopshinal , @gotnull , if any of you could verify that 0.6.1 fixes your problem, I think we can close this issue.

**Comment by gotnull** [comment]
Thanks for the quick bug fix @trond-snekvik. Much appreciated.

I've flashed the 0.6.1 library to the SparkCore and the menu options are now appearing in the Adafruit BLE app.

The problem now is that when I select UART and connect my SparkCore to Termite (I'm using v3.1) I'm not seeing any serial data to/from.

I've triple checked the port, baud rate, data bits and stop bits, etc and they're fine. I've also left the pins in the default configuration and triple checked them also.

Can you confirm you're receiving serial data to/from?

**Comment by trond-snekvik** [comment]
That sounds a bit strange. It works for me, but the Spark seems to be kind of picky about the UART connection, and I sometimes have to setup Termite and then restart the Spark Core before I am actually able to communicate (Termite seems to be left in some zombie state occasionally, where it looks like it is connected, but it won't respond). You could try some local serial stuff on your Spark Core without the BLE, as this sounds like an issue with the Spark. The spark.io forums might be of better help if this is the case.

When you have verified that your Serial communication works between the Spark and your computer, try to connect with the official nRF UART app. I'm not too familiar with the Adafruit app, and it is not officially supported for this port.

I have Termite set for 115200 baud, 8/1, no parity and RTS/CTS flow. When I connect with the nRF UART app, the Spark sends "Sending: Spark Core says hello!" to the computer terminal.

**Comment by gotnull** [comment]
I can successfully change the name of the device by doing "name=foo" and that works just fine.

The serial TX/RX still doesn't seem to be working though. I'll keep at it.

**Comment by trond-snekvik** [comment]
Yes, that seems strange. You could try connecting with a more generic BLE app (such as [LightBlue](https://itunes.apple.com/us/app/lightblue-bluetooth-low-energy/id557428110?mt=8)), and write to the TX characteristic (UUID 6E40**0002**-B5A3-F393-E0A9-E50E24DCCA9E).
